### ISSUE TITLE
react pixelify in ts

### ISSUE THREAD

**Issue by tonynguyenit18** [nikoferro/react-pixelify#5]
Hi Nikoferro. I tried to find your contact but could found any way, so I borrow this issue to contact you.

I am working on a feature which is pixelate a html element, and this repo inspired me. I also convert your Pixelify component to typescript and add your repo link in my repo: https://github.com/tonynguyenit18/react-pixelate.

I want to message to let you know and ask you to let me public my repo. Is it ok?

 Please let me know if you have any question via tonynguyenit18@gmail.com.
 
 Thanks Nikoferro.

**Comment by nikoferro** [comment]
Hey! Sorry for the lack of a reply before. Cool stuff, if you want to go ahead and create a PR to merge both projects with the typings so we avoid having two doing the same thing let me know. In any case thanks for reaching out and crediting the project on your repo and blog. 

Best
Nico
